version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  consensus:
    restart: "${RESTART}"
    build:
      context: ./lighthouse
      dockerfile: ${LH_DOCKERFILE}
      args:
        - BUILD_TARGET=${LH_SRC_BUILD_TARGET}
        - DOCKER_TAG=${LH_DOCKER_TAG}
    image: lighthouse:local
    user: lhconsensus
    stop_grace_period: 1m
    volumes:
      - lhconsensus-data:/var/lib/lighthouse
      - /etc/localtime:/etc/localtime:ro
      - ./${NETWORK}:/configs
    ports:
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/tcp
      - ${CL_P2P_PORT}:${CL_P2P_PORT}/udp
    expose:
      - 5052/tcp
      - 5054/tcp
    networks:
      default:
        aliases:
          - eth2
    <<: *logging
    entrypoint:
      - lighthouse
      - bn
      - --disable-upnp
      - --datadir
      - /var/lib/lighthouse
      - --http
      - --http-address
      - 0.0.0.0
      - --http-port
      - "5052"
      - --port
      - ${CL_P2P_PORT}
      - --target-peers
      - ${LH_PEER_COUNT}
      - --execution-endpoints
      - ${EL_NODE}
      - --eth1-endpoints
      - ${EL_NODE}
      - --debug-level=${LOG_LEVEL}
      - --metrics
      - --metrics-address
      - 0.0.0.0
      - --validator-monitor-auto
      - --testnet-dir
      - /configs
      - --boot-nodes
      - ${ENR}
      - --merge
      - --disable-packet-filter
      - --terminal-total-difficulty-override
      - ${TOTAL_TERMINAL_DIFFICULTY}
      - --fee-recipient
      - ${REWARDS_TO}
      - --http-allow-sync-stalled
    labels:
      - traefik.enable=true
      - traefik.http.routers.cl.service=cl
      - traefik.http.routers.cl.entrypoints=websecure
      - traefik.http.routers.cl.rule=Host(`${CL_HOST}.${DOMAIN}`)
      - traefik.http.routers.cl.tls.certresolver=letsencrypt
      - traefik.http.services.cl.loadbalancer.server.port=5052
  eth:
    image: tianon/true
    restart: "no"
    depends_on:
      - consensus
volumes:
  lhconsensus-data:
