version: "3.4"
x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 10m
      max-file: "3"

services:
  execution:
    restart: "${RESTART}"
    stop_grace_period: 3m
    build:
      context: ./nethermind
      dockerfile: ${NM_DOCKERFILE}
      args:
        - BUILD_TARGET=${NM_SRC_BUILD_TARGET}
        - DOCKER_TAG=${NM_DOCKER_TAG}
    image: nethermind:local
    user: nethermind
    volumes:
      - nmexecution-data:/var/lib/nethermind
      - ./${NETWORK}:/configs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/tcp
      - ${EL_P2P_PORT}:${EL_P2P_PORT}/udp
    expose:
      - ${EL_RPC_PORT}/tcp
      - ${EL_WS_PORT}/tcp
    networks:
      default:
        aliases:
          - eth1
    <<: *logging
    entrypoint:
      - dotnet
      - /nethermind/Nethermind.Runner.dll
      - --datadir
      - /var/lib/nethermind
      - --Init.WebSocketsEnabled
      - "true"
      - --Network.DiscoveryPort
      - ${EL_P2P_PORT}
      - --Network.P2PPort
      - ${EL_P2P_PORT}
      - --JsonRpc.Enabled
      - "true"
      - --JsonRpc.EnabledModules
      - "Web3,Eth,Subscribe,Net,Consensus,Engine"
      - --JsonRpc.Host
      - 0.0.0.0
      - --JsonRpc.Port
      - ${EL_RPC_PORT}
      - --JsonRpc.WebSocketsPort
      - ${EL_WS_PORT}
      - --Sync.FastSync
      - "true"
      - --config
      - ${NETWORK}
      - --Pruning.Enabled
      - "true"
      - --Pruning.CacheMb
      - "4096"
      - --Init.ChainSpecPath
      - "/configs/nethermind_genesis.json"
      - --Merge.Enabled
      - "true"
      - --Merge.TerminalTotalDifficulty
      - ${TOTAL_TERMINAL_DIFFICULTY}
  eth:
    depends_on:
      - execution
volumes:
  nmexecution-data:
